### ISSUE TITLE
Customer Adds Item to Order

### ISSUE THREAD

**Issue by ch0min** [rasm445f/soft-exam-2#17]
As a customer, 
I want to place an order from a restaurant, 
so that I can receive food at my delivery address.

Accept Criteria:

- [ ] Given that I am logged into my account and are viewing a restaurant menu, and if I’m not logged in, notify me to log in.
- [ ] When I select an item
- [ ] Then my order cart should be updated.

**Comment by oTuff** [comment]
maybe update the user story to be more precise about "add an item to order" instead of "place an order"
